# Conky (normal conkies - not always transparent)
match = "class_g = 'Conky'";
blur-background = true;
corner-radius = 6;
opacity = 0.75;
dim = 0.0;
shadow = true;
animations = (
{
    triggers = ["close", "hide"];
    preset = "fly-out";
    direction = "up";
    duration = 1.0;
    },
{
    triggers = ["open", "show"];
    preset = "fly-in";
    delay = 3;
    direction = "up";
    duration = 1.0;
    },
)
