# CONKY with transparent background (no background) like: logo, polaroid conky
# they need 'own_window_class'
# opacity like 0.2 - 0.3 might create interesting effect :)
match = "class_g = 'Conky-nobg'";
blur-background = false;
corner-radius = 0;
opacity = 1.0;
dim = 0.0;
shadow = false;
animations = (
  {
    triggers = ["close", "hide"];
    preset = "disappear";
    duration = 1.0;
    },
{
      triggers = ["open", "show"];
      preset = "appear";
      duration = 1.0;
     },
)

