# JGMENU opacity and corner radius is controlled by jgmenu itself
# Maybe split animations to separate files?
match = "name = 'jgmenu'";
blur-background = true;
opacity = 1.0;
corner-radius = 2;
dim = 0.0;
shadow = true;
animations = (
    {
      triggers = ["close", "hide"];
      preset = "fly-out";
      direction = "up";
      duration = 0.6;
      scale = 0.8;
      
      },
    {
      triggers = ["open", "show"];
      preset = "appear";
      duration = 0.2;
      scale = 0.6;
    }
  )

