rules: (
{ match = "fullscreen"; corner-radius = 0; dim = 0.0; shadow = false;},
{
@include "win-inactive.conf"
},
{
    match = "window_type = 'dropdown_menu'";
    blur-background = false;
    shadow = false;
    corner-radius = 0;
    opacity = 1.0;
},

{
    match = "window_type = 'popup_menu'";
    blur-background = false;
    shadow = false;
    corner-radius = 0;
    opacity = 1.0;
},

{
    match = "window_type = 'popup'";
    blur-background = false;
    shadow = false;
    corner-radius = 0;
    opacity = 1.0;
},

{
    match = "window_type = 'dock'";
    shadow = false;
    corner-radius = 5;
    fade = true;
},

{
    match = "window_type = 'tooltip'";
    shadow = false;
    corner-radius = 2;
    fade = false;
    opacity = 0.90;
    full-shadow = false;
},

{
    match = "window_type = 'splash'";
    shadow = false;
},

{
    match = "window_type = 'dialog'";
    shadow = false;
},

{
    match = "window_type = 'menu'";
    blur-background = false;
    shadow = false;
    corner-radius = 0;
    opacity = 1.0;
},

{
    # Mabox screenshot tool
    match = "class_g = 'slop'";
    opacity = 1;
    shadow = false;
    blur-background = false;
    corner-radius = 0;
},

{
match = "class_g = 'skippy-xd-fix'";
blur-background = false;
opacity = 1.0;
shadow = false;
corner-radius = 0;
},
@include "mabox-animations.conf"
{
match = "name = 'cavatransparent' || name = 'vistransparent'";
blur-background = false;
shadow = false;
animations = (
   {
      triggers = ["hide"];
      preset = "slide-out";
      opacity = 1.0;
      direction = "down";
      duration = 1.2;
      delay = 0.5;
   },
  )
},
{
@include "jgmenu.conf"
},
{
@include "tint2.conf"
},
{
@include "conky.conf"
},
{
@include "conky-nobg.conf"
},
{
@include "notifications.conf"
},
)
