# NOTIFICATIONS
   match = "name = 'xfce4-notifyd'"
   shadow = true;
   dim = 0.0;
   corner-radius = 2;
   animations = (
    {
      triggers = ["close", "hide"];
      preset = "fly-out";
      direction = "up";
      duration = 0.2;
    },
    {
      triggers = ["open", "show"];
      preset = "fly-in";
      direction = "right";
      duration = 0.2;
     }
  )
