# TINT2 opacity, corner-radius is controlled by tint2 itself
# but corner-radius might be handy here
match = "name = 'tint2'";
blur-background = true;
corner-radius = 4;
opacity = 1.0;
dim = 0.0;
shadow = false;

