#!/bin/bash

build() {
    add_module "cdrom"
    add_module "loop"
    add_module "dm-snapshot"
    add_module "dm-crypt"
    add_module "overlay"

    add_runscript

    add_binary /usr/lib/udev/cdrom_id
    add_binary blockdev
    add_binary cryptsetup
    add_binary dmsetup
    add_binary losetup
    add_binary mountpoint
    add_binary truncate
    add_binary gpg
    add_binary grep

    # cryptsetup's own runtime deps -- verified against the real
    # /usr/lib/initcpio/install/encrypt on this host.
    add_binary '/usr/lib/libgcc_s.so.1'
    add_binary '/usr/lib/ossl-modules/legacy.so'

    add_file /usr/lib/udev/rules.d/60-cdrom_id.rules
    add_file /usr/lib/udev/rules.d/10-dm.rules
    add_file /usr/lib/udev/rules.d/95-dm-notify.rules
    if [[ $MISO_GNUPG_FD ]]; then
        mkdir -p "$BUILDROOT$dest"/gpg
        gpg --homedir "$BUILDROOT$dest"/gpg --import <&$MISO_GNUPG_FD
    fi
}

# vim: set ft=sh ts=4 sw=4 et:
