# Sidearea width/height in pixels (set to 0 to disable side actions)
sidearea=10

# Commands 
# Center area (or whole desktop if sidearea = 0)
cmd_center=none

# Sidearea commands:
cmd_topleft=show_desktop
cmd_top="jgdesktops -s"
cmd_topright="mb-music -s"

cmd_left="mb-jgtools places 2>/dev/null"
cmd_right="mb-jgtools right 2>/dev/null"

cmd_bottomleft="skippy-xd --expose"
cmd_bottom="skippy-xd --paging"
cmd_bottomright="mb-jgtools mblogout"

# Editor (for areaclick editconf command)
editor=geany
