jgmenu_theme=MBcolors
jgmenu_use_icons=true
jgmenu_use_borders=false
jgmenu_icon_theme="Numix-Square"
places_softwarepipe=true
places_sysinfopipe=true
places_menusettingspipe=true
places_quicknav=true
places_tint2pipe=true
places_conkypipe=true
places_jgdesktops=false
places_jgdeskmngr=true
places_jgdeskgrid=true
places_sshpipe=false
places_bookmarks=true
panels_heightpos=full
menu_font_family='Ubuntu Regular'
menu_font_size=10
menu_sep_font_family='Ubuntu Bold'
menu_sep_font_size=11
arrow_string=''
arrow_string_left=''
jgtools_border=0
jgtools_padding=8
jgtools_radius=2
submenu_spacing=4
panels_topmargin=40
panels_heightpos=full
phwmon_monitor=true
phwmon_cpu=true
phwmon_mem=true
phwmon_swap=false
phwmon_net=true
phwmon_io=false
phwmon_bgcolor=#30303080
phwmon_alertcolor=#ff0000
phwmon_cpucolor=#70b433
phwmon_memcolor=#efc541
phwmon_swapcolor=#ff81ca
phwmon_netcolor=#368aeb
phwmon_iocolor=#ff5e56
phwmon_iconsize=64
picom_renderer=glx
color_ok=#EEEEEE
disk_limit=90
big_pkgs=0
ok_icon=󰞑
ok_fgcolor=#008a00
warn_fgcolor=#FFFFFF
warn_bgcolor=#bd1e24
dir_size_monitor=n
floatpanel_margin=2
floatpanel_width=95

places_vboxes=false
item_height_factor=200

conky_leftclick=on
conky_rightclick=on

logo_in_color=#32B557
logo_out_color=#F8F8FF
logo_in_opacity=0.7
logo_out_opacity=0.7
