# User wallpapers directories - one per line
# Used by "Random", "Choose wallpaper" PCmanFM wrapper, "Slideshow", Preview and set" utils
# From File Manager set wallpapers using context (right click) menu 
~/wallpapers
