# Autogenerate color themes on wallpaper change? yes or no
wall2themes=no
# conky preffered bg color dark, light or none (none = not generate/change colorscheme)
wall2themes_conky=dark
# OB window decoration preferred color style: dark, light or none
wall2themes_ob=light
# Menu prefferred bg color dark, light or none (not generate/change colorscheme)
wall2themes_menu=light
# Accent color dark, light or none
wall2themes_accent=dark
# PyRadio preferred bg color dark, light or none (not generate/change colorscheme)
wall2themes_pyradio=dark
# User wallpaper dir
user_wallpapers_dir=~/wallpapers
# Show related tools (show or hide)
related_tools=hide
# Colorizer size: full or compact
colorizer_size=compact
# Action for rootmenucolors: accent or select
rootcolors=select
# Different colors for each/some Conkys: yes or no
conky_diff_colors=no
# Gradients: change openbox theme? (active window titlebar)
gradient_obtheme=yes
# Gradients: change menu/panels background?
gradient_menu=no

